### ISSUE TITLE
Incorrect value for leech

### ISSUE THREAD

**Issue by AceAzzermeen** [mynian/ConvertRatings#49]
In the tooltip of my item it displays 325 leech are 2,95% but the character sheet tells me that it is only 2,2%

I have no other sources of leech.

**Comment by tonydero** [comment]
Not sure if this addon is still under active development/maintenance, but I can corroborate AceAzzermeen's findings. Have one piece of gear with 401 Leech, no other sources, and the addon says it should provide 3.65%, but it actually provides 2.71% on the character pane.

It seems Leech is actually around 150/1% instead of 110/1%?

Edit: Leech coefficients were changed to make leech 25% less effective in 10.1, so the leech values in leechtab just need to be divided by 0.75 to be accurate again.

Edit 2: Dividing by 0.75 did not produce accurate results after all. It's still off slightly. The "25%" mentioned in the patch notes might have been an approximation, so the values may just need to be calculated again. Where did you get the values for the tables to begin with?

**Comment by mynian** [comment]
leech values have been updated in newest version

Sorry for the delay, github stopped sending me emails on new tickets for some reason.
