### ISSUE TITLE
[Lua Error] Conflict with BankItems

### ISSUE THREAD

**Issue by Lanrutcon** [mynian/ConvertRatings#7]
According to a user on [Curse.com](https://mods.curse.com/addons/wow/255616-convert-ratings?comment=9), it seems BankItems addon is causing some conflicts with ConvertRatings.

The addon 'blows up' when calling the function "**GetItemInfo**" (_Usage: GetItemInfo(itemID|"name"|"itemlink")_).

My guess is that '_itemLink_' (the argument that is been giving to "**GetItemInfo**") is _nil_ in these situations.

**Comment by mynian** [comment]
installed bankitems

unable to reproduce

Asked for more info from poster

**Comment by BlueNightSky** [comment]
I just open the backpack, try to sell some unwanted things, sometimes this error occurs.
There was also an error when auctioning items, but not every time.

**Comment by mynian** [comment]
After looking again at your posting, I was able to determine that you are using an alpha version of that particular addon. 

My guess is that there is an error in the alpha code for that addon. That particular addon does not have a stable legion release version.

Since I am unable to reproduce the error with the last stable release version, I am going to mark this as a non-fix issue. If this error persists after that addon releases a legion stable version, please feel free to resubmit an issue.
